language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - 4.4.5
script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - cd styleguide/structure/_node-files
  - npm install tape faucet browserify nightwatch
  - npm install
  - cd ../_tests
  - node structure-node-dependencies.js
  - node structure-node-modules.js
  - node structure-front-scripts.js
